const JOB_KEY='paklaunce_week4_jobs';
const PROPOSAL_KEY='paklaunce_week4_proposals';

const defaultJobs=[
{id:101,title:'Build a modern business website for a local company',category:'Web Development',budgetMin:300,budgetMax:600,description:'We need a fast, responsive company website with a professional homepage, services pages, contact form and basic SEO setup. The site should be easy to maintain after launch.',skills:['HTML','CSS','JavaScript','WordPress'],posted:'2026-09-27',proposals:8,client:'Ahsan Enterprises',location:'Peshawar'},
{id:102,title:'Design a complete brand identity for a startup',category:'Graphic Design',budgetMin:150,budgetMax:350,description:'Create a clean startup identity including logo concepts, color system, typography and social media assets. We already have the product direction and need a polished visual system.',skills:['Figma','Branding','Illustrator','Logo Design'],posted:'2026-09-26',proposals:14,client:'Northstar Labs',location:'Islamabad'},
{id:103,title:'Flutter mobile app for a service marketplace',category:'Mobile App Development',budgetMin:700,budgetMax:1400,description:'Looking for a Flutter developer to build the first version of a two-sided marketplace app. Authentication, profiles, listings, search and API integration are required.',skills:['Flutter','Dart','Firebase','REST API'],posted:'2026-09-25',proposals:6,client:'PakServe',location:'Lahore'},
{id:104,title:'Analyze sales data and create an executive dashboard',category:'Data Analysis',budgetMin:200,budgetMax:450,description:'Clean and analyze monthly sales data, identify trends and create a clear dashboard with useful KPIs for management reporting.',skills:['Excel','Python','SQL','Power BI'],posted:'2026-09-24',proposals:11,client:'Khyber Traders',location:'Peshawar'},
{id:105,title:'Run a 30-day digital marketing campaign',category:'Digital Marketing',budgetMin:250,budgetMax:500,description:'Plan and execute a focused digital campaign for a Pakistani e-commerce brand. Deliverables include content calendar, campaign setup, reporting and optimization recommendations.',skills:['SEO','Meta Ads','Content Strategy','Analytics'],posted:'2026-09-23',proposals:19,client:'Urban Cart',location:'Karachi'},
{id:106,title:'Fix and optimize an existing React dashboard',category:'Web Development',budgetMin:120,budgetMax:300,description:'Improve performance, fix responsive layout issues and clean up a React dashboard with several existing UI bugs. Experience with modern React is preferred.',skills:['React','JavaScript','CSS','Performance'],posted:'2026-09-22',proposals:9,client:'MetricFlow',location:'Rawalpindi'}
];

function jobsLoad(){return JSON.parse(localStorage.getItem(JOB_KEY)||'null')||defaultJobs}
function jobsSave(v){localStorage.setItem(JOB_KEY,JSON.stringify(v))}
function proposalsLoad(){return JSON.parse(localStorage.getItem(PROPOSAL_KEY)||'[]')}
function proposalsSave(v){localStorage.setItem(PROPOSAL_KEY,JSON.stringify(v))}
function moneyRange(j){return `$${j.budgetMin}–$${j.budgetMax}`}
function daysAgo(date){const d=Math.max(0,Math.floor((Date.now()-new Date(date+'T12:00:00').getTime())/86400000));return d===0?'Today':d===1?'1 day ago':`${d} days ago`}
function jobCard(j){return `<article class="card job-card"><div class="job-top"><span class="tag">${escapeHTML(j.category)}</span><span class="muted job-date">${daysAgo(j.posted)}</span></div><h3>${escapeHTML(j.title)}</h3><p class="muted job-description">${escapeHTML(j.description)}</p><div class="pill-row">${j.skills.map(s=>`<span class="tag">${escapeHTML(s)}</span>`).join('')}</div><div class="job-meta"><div><span class="muted">Budget</span><strong>${moneyRange(j)}</strong></div><div><span class="muted">Proposals</span><strong>${j.proposals}</strong></div><div><span class="muted">Location</span><strong>${escapeHTML(j.location)}</strong></div></div><div class="card-actions"><a class="btn primary" href="job.html?id=${j.id}">View Job</a><a class="btn" href="submit-proposal.html?job=${j.id}">Apply</a></div></article>`}

function initJobs(){
 nav('jobs');
 const q=new URLSearchParams(location.search);const search=document.getElementById('jobSearch');const cat=document.getElementById('jobCategory');const sort=document.getElementById('jobSort');
 if(q.get('q')) search.value=q.get('q'); if(q.get('category')) cat.value=q.get('category');
 function render(){let list=[...jobsLoad()];const term=(search.value||'').toLowerCase().trim();const c=cat.value||'All';const s=sort.value||'newest';if(term)list=list.filter(j=>(j.title+' '+j.category+' '+j.description+' '+j.skills.join(' ')+' '+j.client).toLowerCase().includes(term));if(c!=='All')list=list.filter(j=>j.category===c);if(s==='budget-low')list.sort((a,b)=>a.budgetMin-b.budgetMin);if(s==='budget-high')list.sort((a,b)=>b.budgetMax-a.budgetMax);if(s==='proposals')list.sort((a,b)=>a.proposals-b.proposals);if(s==='newest')list.sort((a,b)=>new Date(b.posted)-new Date(a.posted));document.getElementById('jobGrid').innerHTML=list.length?list.map(jobCard).join(''):`<div class="card empty" style="grid-column:1/-1"><h3>No jobs found</h3><p>Try another search term or category.</p></div>`;document.getElementById('jobCount').textContent=`${list.length} project${list.length===1?'':'s'} found`}
 [search,cat,sort].forEach(x=>x?.addEventListener('input',render));render();
}

function initJobDetail(){
 const id=Number(new URLSearchParams(location.search).get('id'));const j=jobsLoad().find(x=>x.id===id)||jobsLoad()[0];if(!j)return;
 document.title=`${j.title} — Paklaunce`; document.getElementById('jobCategory').textContent=j.category;document.getElementById('jobTitle').textContent=j.title;document.getElementById('jobDescription').textContent=j.description;document.getElementById('jobBudget').textContent=moneyRange(j);document.getElementById('jobProposals').textContent=j.proposals;document.getElementById('jobPosted').textContent=daysAgo(j.posted);document.getElementById('jobClient').textContent=j.client;document.getElementById('jobLocation').textContent=j.location;document.getElementById('jobSkills').innerHTML=j.skills.map(s=>`<span class="tag">${escapeHTML(s)}</span>`).join('');document.querySelectorAll('[data-apply-link]').forEach(a=>a.href=`submit-proposal.html?job=${j.id}`);nav('jobs');
}

function initPostJob(){
 nav('postjob');const form=document.getElementById('jobForm');form.addEventListener('submit',e=>{e.preventDefault();const values={title:jobTitle.value.trim(),category:jobCategory.value,description:jobDescription.value.trim(),budgetMin:Number(budgetMin.value),budgetMax:Number(budgetMax.value),skills:jobSkills.value.split(',').map(x=>x.trim()).filter(Boolean)};let error='';if(!values.title||!values.category||!values.description||!values.skills.length)error='Please complete all required fields.';else if(values.budgetMin<=0||values.budgetMax<=0||values.budgetMin>values.budgetMax)error='Please enter a valid budget range.';if(error){formError.textContent=error;formError.style.display='block';return}const list=jobsLoad();const item={id:Date.now(),...values,posted:new Date().toISOString().slice(0,10),proposals:0,client:'Basit Khan',location:'Pakistan'};list.unshift(item);jobsSave(list);formError.style.display='none';toast('Job posted successfully');setTimeout(()=>location.href=`job.html?id=${item.id}`,450)})
}

function initProposal(){
 nav('jobs');const id=Number(new URLSearchParams(location.search).get('job'));const j=jobsLoad().find(x=>x.id===id)||jobsLoad()[0];if(!j)return;document.getElementById('proposalJobTitle').textContent=j.title;document.getElementById('proposalBudget').textContent=moneyRange(j);document.getElementById('proposalSkills').innerHTML=j.skills.map(s=>`<span class="tag">${escapeHTML(s)}</span>`).join('');const form=document.getElementById('proposalForm');form.addEventListener('submit',e=>{e.preventDefault();const cover=coverLetter.value.trim(),price=Number(proposedPrice.value),delivery=proposalDelivery.value,experience=relevantExperience.value.trim();let error='';if(cover.length<30)error='Cover letter should contain at least 30 characters.';else if(!price||price<=0)error='Enter a valid proposed price.';else if(!delivery)error='Select a delivery time.';else if(experience.length<20)error='Add a little more relevant experience.';if(error){formError.textContent=error;formError.style.display='block';return}const p={id:Date.now(),jobId:j.id,jobTitle:j.title,coverLetter:cover,price,delivery,experience,status:'Pending',submitted:new Date().toISOString().slice(0,10)};const list=proposalsLoad();list.unshift(p);proposalsSave(list);jobsSave(jobsLoad().map(x=>x.id===j.id?{...x,proposals:x.proposals+1}:x));formError.style.display='none';toast('Proposal submitted');setTimeout(()=>location.href='my-proposals.html',500)})
}

function proposalBadge(status){return `<span class="status ${status.toLowerCase()}">${status}</span>`}
function initProposals(){nav('proposals');const box=document.getElementById('proposalList');function render(){const list=proposalsLoad();box.innerHTML=list.length?list.map(p=>`<article class="card proposal-card"><div><span class="tag">Proposal #${p.id.toString().slice(-5)}</span><h3>${escapeHTML(p.jobTitle)}</h3><p class="muted">Submitted ${p.submitted}</p></div><div class="proposal-summary"><div><span class="muted">Proposed</span><strong>$${p.price}</strong></div><div><span class="muted">Delivery</span><strong>${escapeHTML(p.delivery)}</strong></div><div>${proposalBadge(p.status)}</div></div><details><summary>View proposal</summary><p>${escapeHTML(p.coverLetter)}</p><p class="muted"><strong>Experience:</strong> ${escapeHTML(p.experience)}</p><div class="card-actions"><button class="btn" data-status="Accepted" data-id="${p.id}">Mark Accepted</button><button class="btn danger" data-status="Rejected" data-id="${p.id}">Mark Rejected</button></div></details></article>`).join(''):`<div class="card empty"><h3>No proposals yet</h3><p>Find a job and submit your first proposal.</p><a class="btn primary" href="jobs.html">Find Jobs</a></div>`;box.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{const updated=proposalsLoad().map(p=>p.id==b.dataset.id?{...p,status:b.dataset.status}:p);proposalsSave(updated);render();toast(`Proposal marked ${b.dataset.status}`)})}render()}
Object.assign(window,{jobsLoad,jobsSave,proposalsLoad,proposalsSave,jobCard,initJobs,initJobDetail,initPostJob,initProposal,initProposals});
