const KEY='paklaunce_week3';
const defaultProfile={name:'Basit Khan',title:'Full-Stack Developer',bio:'I build fast, scalable and polished web applications for startups and growing businesses across Pakistan.',skills:['JavaScript','React','Node.js','PHP','MySQL'],experience:'3+ years',rating:4.9,reviews:128,location:'Pakistan'};
const defaultServices=[
{id:1,title:'I will build a modern responsive website',category:'Web Development',description:'Professional responsive website with clean UI, fast performance and deployment support.',price:150,delivery:'5 days',skills:['HTML','CSS','JavaScript'],rating:4.9,reviews:72},
{id:2,title:'I will design a premium brand identity',category:'Graphic Design',description:'Complete visual identity including logo concepts, colors and brand assets.',price:80,delivery:'4 days',skills:['Figma','Branding','Illustrator'],rating:4.8,reviews:44},
{id:3,title:'I will create a cross-platform mobile app',category:'Mobile App Development',description:'Flutter mobile application with clean architecture and responsive interfaces.',price:250,delivery:'10 days',skills:['Flutter','Dart','Firebase'],rating:5,reviews:31}
];
function load(){return JSON.parse(localStorage.getItem(KEY)||'{}')}function save(d){localStorage.setItem(KEY,JSON.stringify(d))}function profile(){return {...defaultProfile,...load().profile}}function services(){return load().services||defaultServices}function setServices(s){const d=load();d.services=s;save(d)}
function toast(msg){const t=document.querySelector('.toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function escapeHTML(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function nav(active){document.querySelectorAll('.links a').forEach(a=>a.classList.toggle('active',a.dataset.page===active))}
function serviceCard(s){return `<article class="card service-card"><div class="service-thumb">✦</div><div class="top"><img class="avatar" src="assets/profile.svg" alt="Profile"><div><strong>${escapeHTML(profile().name)}</strong><div class="muted" style="font-size:12px">${escapeHTML(profile().title)}</div></div></div><h3 style="margin:0">${escapeHTML(s.title)}</h3><span class="tag">${escapeHTML(s.category)}</span><div class="pill-row">${s.skills.map(x=>`<span class="tag">${escapeHTML(x)}</span>`).join('')}</div><div><span class="rating">★ ${s.rating}</span> <span class="muted">(${s.reviews} reviews)</span></div><div style="display:flex;justify-content:space-between;align-items:center"><div><span class="muted">Starting at</span><div class="price">$${s.price}</div></div><span class="muted">${escapeHTML(s.delivery)}</span></div><div class="card-actions"><a class="btn primary" href="service.html?id=${s.id}">View Service</a><a class="btn" href="freelancer.html">Profile</a></div></article>`}
function renderServices(){const box=document.querySelector('#serviceGrid');if(!box)return;let list=services();const q=(document.querySelector('#search')?.value||'').toLowerCase();const cat=document.querySelector('#category')?.value||'All';const sort=document.querySelector('#sort')?.value||'default';if(q)list=list.filter(s=>(s.title+' '+s.category+' '+s.skills.join(' ')).toLowerCase().includes(q));if(cat!=='All')list=list.filter(s=>s.category===cat);if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);box.innerHTML=list.length?list.map(serviceCard).join(''):`<div class="card empty" style="grid-column:1/-1">No services match your search.</div>`}
function initMarketplace(){nav('services');['search','category','sort'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderServices));renderServices()}
function fillProfile(){const p=profile();document.querySelectorAll('[data-profile-name]').forEach(e=>e.textContent=p.name);document.querySelectorAll('[data-profile-title]').forEach(e=>e.textContent=p.title);document.querySelectorAll('[data-profile-bio]').forEach(e=>e.textContent=p.bio);document.querySelectorAll('[data-profile-rating]').forEach(e=>e.textContent=p.rating);document.querySelectorAll('[data-profile-reviews]').forEach(e=>e.textContent=p.reviews);const skills=document.querySelector('#profileSkills');if(skills)skills.innerHTML=p.skills.map(s=>`<span class="tag">${escapeHTML(s)}</span>`).join('')}
function initProfile(){nav('profile');fillProfile();const p=profile();const s=services();const grid=document.querySelector('#profileServices');if(grid)grid.innerHTML=s.map(serviceCard).join('')}
function initEdit(){nav('profile');const p=profile();['name','title','bio','experience','location'].forEach(k=>{const e=document.getElementById(k);if(e)e.value=p[k]||''});document.getElementById('skills').value=p.skills.join(', ');document.getElementById('profileForm').addEventListener('submit',e=>{e.preventDefault();const p={...profile(),name:name.value.trim(),title:title.value.trim(),bio:bio.value.trim(),experience:experience.value.trim(),location:location.value.trim(),skills:skills.value.split(',').map(x=>x.trim()).filter(Boolean)};if(!p.name||!p.title||!p.bio){document.getElementById('formError').style.display='block';return}document.getElementById('formError').style.display='none';const d=load();d.profile=p;save(d);toast('Profile updated successfully');setTimeout(()=>location.href='profile.html',500)})}
function initCreate(){nav('create');document.getElementById('serviceForm').addEventListener('submit',e=>{e.preventDefault();let valid=true;document.querySelectorAll('[required]').forEach(x=>{if(!x.value.trim()){valid=false}});if(!valid){document.getElementById('formError').style.display='block';return}document.getElementById('formError').style.display='none';const s={id:Date.now(),title:serviceTitle.value.trim(),category:serviceCategory.value,description:serviceDescription.value.trim(),price:Number(servicePrice.value),delivery:delivery.value,skills:serviceSkills.value.split(',').map(x=>x.trim()).filter(Boolean),rating:5,reviews:0};const list=services();list.unshift(s);setServices(list);toast('Service published successfully');setTimeout(()=>location.href='my-services.html',500)})}
function initMyServices(){nav('myservices');const box=document.querySelector('#myServices');function render(){const list=services();box.innerHTML=list.map(s=>`<article class="card" style="display:grid;grid-template-columns:150px 1fr auto;gap:18px;align-items:center"><div class="service-thumb">✦</div><div><span class="tag">${escapeHTML(s.category)}</span><h3>${escapeHTML(s.title)}</h3><div class="muted">$${s.price} · ${s.delivery} · ★ ${s.rating}</div></div><div class="card-actions"><a class="btn" href="service.html?id=${s.id}">View</a><button class="btn danger" data-delete="${s.id}">Delete</button></div></article>`).join('');box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this service?')){setServices(services().filter(s=>s.id!=b.dataset.delete));render();toast('Service deleted')}})}render()}
function initDetail(){const id=Number(new URLSearchParams(location.search).get('id'));const s=services().find(x=>x.id===id)||services()[0];if(!s)return;document.querySelector('#detailTitle').textContent=s.title;document.querySelector('#detailDescription').textContent=s.description;document.querySelector('#detailCategory').textContent=s.category;document.querySelector('#detailPrice').textContent='$'+s.price;document.querySelector('#detailDelivery').textContent=s.delivery;document.querySelector('#detailRating').textContent='★ '+s.rating+' ('+s.reviews+' reviews)';document.querySelector('#detailSkills').innerHTML=s.skills.map(x=>`<span class="tag">${escapeHTML(x)}</span>`).join('');document.querySelector('#contactBtn').onclick=()=>document.querySelector('#contactModal').classList.add('show');document.querySelector('#closeModal').onclick=()=>document.querySelector('#contactModal').classList.remove('show')}
function initHome(){nav('home');document.querySelector('#homeServices')?.replaceChildren(...services().slice(0,3).map(s=>{const d=document.createElement('div');d.innerHTML=serviceCard(s);return d.firstElementChild}));document.querySelector('#homeSearch')?.addEventListener('submit',e=>{e.preventDefault();location.href='services.html?q='+encodeURIComponent(homeQuery.value)})}
document.addEventListener('DOMContentLoaded',()=>{fillProfile();if(document.body.dataset.page==='home')initHome();if(document.body.dataset.page==='services')initMarketplace();if(document.body.dataset.page==='profile')initProfile();if(document.body.dataset.page==='edit')initEdit();if(document.body.dataset.page==='create')initCreate();if(document.body.dataset.page==='myservices')initMyServices();if(document.body.dataset.page==='detail')initDetail()});
